### ISSUE TITLE
"builtins.ValueError: too many values to unpack (expected 2)" traceback on connecting to network

### ISSUE THREAD

**Issue by eythian** [tkluck/pac4cli#42]
When my computer connects, I see this in syslog:

```
Sep 17 16:20:55 taniwha pac4cli[18693]: Unhandled Error
Sep 17 16:20:55 taniwha pac4cli[18693]: Traceback (most recent call last):
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
Sep 17 16:20:55 taniwha pac4cli[18693]:     return callWithContext({"system": lp}, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return func(*args,**kw)
Sep 17 16:20:55 taniwha pac4cli[18693]: --- <exception caught here> ---
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
Sep 17 16:20:55 taniwha pac4cli[18693]:     why = selectable.doRead()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 205, in doRead
Sep 17 16:20:55 taniwha pac4cli[18693]:     return self._dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 211, in _dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     rval = self.protocol.dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2125, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     return basic.LineReceiver.dataReceived(self, data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 578, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     why = self.rawDataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2132, in rawDataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     self._transferDecoder.dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 1614, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     finishCallback(data[contentLength:])
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2029, in _finishRequestBody
Sep 17 16:20:55 taniwha pac4cli[18693]:     self.allContentReceived()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     req.requestReceived(command, path, version)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     self.process()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/pac4cli/pac4cli.py", line 38, in process
Sep 17 16:20:55 taniwha pac4cli[18693]:     host, port = host.split(':')
Sep 17 16:20:55 taniwha pac4cli[18693]: builtins.ValueError: too many values to unpack (expected 2)
Sep 17 16:20:55 taniwha pac4cli[18693]: Unhandled Error
Sep 17 16:20:55 taniwha pac4cli[18693]: Traceback (most recent call last):
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
Sep 17 16:20:55 taniwha pac4cli[18693]:     return callWithContext({"system": lp}, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return func(*args,**kw)
Sep 17 16:20:55 taniwha pac4cli[18693]: --- <exception caught here> ---
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
Sep 17 16:20:55 taniwha pac4cli[18693]:     why = selectable.doRead()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 205, in doRead
Sep 17 16:20:55 taniwha pac4cli[18693]:     return self._dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 211, in _dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     rval = self.protocol.dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2125, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     return basic.LineReceiver.dataReceived(self, data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 578, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     why = self.rawDataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2132, in rawDataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     self._transferDecoder.dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 1614, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     finishCallback(data[contentLength:])
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2029, in _finishRequestBody
Sep 17 16:20:55 taniwha pac4cli[18693]:     self.allContentReceived()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     req.requestReceived(command, path, version)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     self.process()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/pac4cli/pac4cli.py", line 38, in process
Sep 17 16:20:55 taniwha pac4cli[18693]:     host, port = host.split(':')
Sep 17 16:20:55 taniwha pac4cli[18693]: builtins.ValueError: too many values to unpack (expected 2)
Sep 17 16:20:55 taniwha pac4cli[18693]: Unhandled Error
Sep 17 16:20:55 taniwha pac4cli[18693]: Traceback (most recent call last):
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
Sep 17 16:20:55 taniwha pac4cli[18693]:     return callWithContext({"system": lp}, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return func(*args,**kw)
Sep 17 16:20:55 taniwha pac4cli[18693]: --- <exception caught here> ---
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
Sep 17 16:20:55 taniwha pac4cli[18693]:     why = selectable.doRead()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 205, in doRead
Sep 17 16:20:55 taniwha pac4cli[18693]:     return self._dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 211, in _dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     rval = self.protocol.dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2125, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     return basic.LineReceiver.dataReceived(self, data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 578, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     why = self.rawDataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2132, in rawDataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     self._transferDecoder.dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 1614, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     finishCallback(data[contentLength:])
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2029, in _finishRequestBody
Sep 17 16:20:55 taniwha pac4cli[18693]:     self.allContentReceived()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     req.requestReceived(command, path, version)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     self.process()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/pac4cli/pac4cli.py", line 38, in process
Sep 17 16:20:55 taniwha pac4cli[18693]:     host, port = host.split(':')
Sep 17 16:20:55 taniwha pac4cli[18693]: builtins.ValueError: too many values to unpack (expected 2)
Sep 17 16:20:55 taniwha pac4cli[18693]: Unhandled Error
Sep 17 16:20:55 taniwha pac4cli[18693]: Traceback (most recent call last):
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
Sep 17 16:20:55 taniwha pac4cli[18693]:     return callWithContext({"system": lp}, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
Sep 17 16:20:55 taniwha pac4cli[18693]:     return func(*args,**kw)
Sep 17 16:20:55 taniwha pac4cli[18693]: --- <exception caught here> ---
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
Sep 17 16:20:55 taniwha pac4cli[18693]:     why = selectable.doRead()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 205, in doRead
Sep 17 16:20:55 taniwha pac4cli[18693]:     return self._dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 211, in _dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     rval = self.protocol.dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2125, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     return basic.LineReceiver.dataReceived(self, data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 578, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     why = self.rawDataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2132, in rawDataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     self._transferDecoder.dataReceived(data)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 1614, in dataReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     finishCallback(data[contentLength:])
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2029, in _finishRequestBody
Sep 17 16:20:55 taniwha pac4cli[18693]:     self.allContentReceived()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     req.requestReceived(command, path, version)
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
Sep 17 16:20:55 taniwha pac4cli[18693]:     self.process()
Sep 17 16:20:55 taniwha pac4cli[18693]:   File "/usr/lib/python3/dist-packages/pac4cli/pac4cli.py", line 38, in process
Sep 17 16:20:55 taniwha pac4cli[18693]:     host, port = host.split(':')
Sep 17 16:20:55 taniwha pac4cli[18693]: builtins.ValueError: too many values to unpack (expected 2)
```

Installed from the PPA:

```
$ apt-cache policy pac4cli
pac4cli:
  Geïnstalleerd: 0.1ubuntu2+git101~ubuntu18.04.1
```

**Comment by tkluck** [comment]
Thanks for reporting @eythian ! That looks like maybe an IP6 address that's being sent as the hostname. I have a patch ready, that I will test and push later today.

**Comment by tkluck** [comment]
@kdehairy just merged the fix to this and I pushed it to launchpad for distribution on ubuntu. I'll close this issue but feel free to re-open if you still see this issue on `0.1ubuntu2+git104~ubuntu18.04.1`.
